name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: depends
      run: apt install premake5
    - name: configure
      run: premake5 gmake2
    - name: make
      run: make
