name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: depends
      run: |
        sudo apt install curl
        curl -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz
        tar xvzf premake.tar.gz
        ls

    - name: configure
      run: premake5 gmake2
    - name: make
      run: make
